message_dispatcher_port: 65000

nick: jabbot
admin:
  - gugod

irc:
  frontend_port: 65123
  networks:
    - freenode
  freenode:
    nick: jabbot
    server: chat.freenode.net
    port: 6667
    channels:
      - jabbot
 
feeds:
  - fortune
feeds_fortune_url: http://gugod.org/fortune.cgi
feeds_fortune_delay: 10
feeds_fortune_appendurl: yes
feeds_fortune_shorturl: yes
feeds_fortune_channels:
  - freenode:jabbot
  - localhost:jabbot

default_encoding: utf8
# channel_encoding_freenode_jabbot3: big5
