# vim:et:sw=2:

nick: jabbot

irc:
  listen: 127.0.0.1:15101
  networks:
    freenode:
      nick: jabbot
      server: chat.freenode.net
      port: 6667
      channels:
        - jabbot

plugins:
  - zh_tw::RandomChatbot
  - zh_tw::Thsrc
 
feeds:
  jabbot-commits:
    type: atom
    url:  http://github.com/feeds/gugod/commits/jabbot/master
    showAuthor: true
    appendurl: true
    shorturl: true
    publish_to:
      - "freenode:jabbot"

cpanfeeds:
  CPAN-Upload:
    type: rss
    url: 'http://search.cpan.org/uploads.rdf'
    publish_to:
      - "freenode:chupei.pm"
