# vim:et:sw=2:
message_dispatcher_port: 65000

nick: asdfasdf
admin:
  - c9s

irc:
  frontend_port: 65123
  networks:
    - freenode
  freenode:
    nick: asdfasdf
    server: chat.freenode.net
    port: 6667
    channels:
      - bottest
 
feeds:
  jabbot-commits:
    type: atom
    url:  http://github.com/feeds/gugod/commits/jabbot/master
    showAuthor: true
    appendurl: true
    shorturl: true
    publish_to:
      - "freenode:jabbot"

cpanfeeds:
  recent:
    type: rss
    url: 'http://unknownplace.org/cpanrecent/rss'
    publish_to:
      - "freenode:bottest"

default_encoding: utf8
# channel_encoding_freenode_jabbot3: big5
