# vim:et:sw=2:

nick: jabbot

irc:
  listen: 127.0.0.1:15101
  networks:
    freenode:
      nick: jabbot
      server: chat.freenode.net
      port: 6667
      channels:
        - jabbot

plugins: []
  # - HandlinoRedmine
  # - en_us::Facts
  # - en_us::Eliza
  # - zh_tw::RandomChatbot
  # - zh_tw::Thsrc
  # - zh_tw::Polite
  # - Math
  # - zh_tw::TaiwanLotto
  # - zh_tw::DateDay
 
feeds:
  jabbot-commits:
    type: atom
    url:  http://github.com/feeds/gugod/commits/jabbot/master
    showAuthor: true
    appendurl: true
    shorturl: true
    publish_to:
      - "freenode:jabbot"

cpantw:
  publish_to:
    - "freenode:#chupei.pm"
    - "freenode:#jabbot"

twitter:
  username:
  password:
  track: perl,jabbot
  publish_to:
    - "freenode:#chupei.pm"
    - "freenode:#jabbot"
