message_dispatcher_port: 65000
irc_daemon_port: 65123
irc_networks:
- freenode
- ircnet
irc_freenode_server: irc.freenode.net
irc_ircnet_server: irc.ircnet.net
nick: jabbot3
admin:
- gugod
- zcecil
irc_channels:
- jabbot3


