# vim:et:sw=2:
message_dispatcher_port: 65000

nick: jabbot
admin:
  - gugod

irc:
  frontend_port: 15101
  networks:
    freenode:
      nick: jabbot
      server: chat.freenode.net
      port: 6667
      channels:
        - jabbot

plugins:
  - zh_tw::RandomChatbot
 
feeds:
  jabbot-commits:
    type: atom
    url:  http://github.com/feeds/gugod/commits/jabbot/master
    showAuthor: true
    appendurl: true
    shorturl: true
    publish_to:
      - "freenode:jabbot"

cpanfeeds:
  CPAN-Upload:
    type: rss
# url: 'http://unknownplace.org/cpanrecent/rss'
    url: 'http://search.cpan.org/uploads.rdf'
    publish_to:
      - "freenode:chupei.pm"

default_encoding: utf8
# channel_encoding_freenode_jabbot3: big5
