irc_networks:
- ircnet
- freenode
nick: jabbot3
admin:
- gugod
- zcecil
irc_ircnet_server: irc.seed.net.tw
irc_channels:
- freenode:svk
- ircnet:osxchat
- ircnet:ntucsie
- ircnet:elixus
- ircnet:perl.tw
- ircnet:bsdchat

feeds:
- useperl
- cpan
- freshports
- versiontracker
- svk

feeds_svk_url: http://svn.clkao.org/svnweb/svk/rss/
feeds_svk_channels:
- freenode:svk
feeds_useperl_url: http://use.perl.org/index.rdf
feeds_useperl_channels:
- ircnet:perl.tw
feeds_cpan_url: http://search.cpan.org/recent.rdf
feeds_cpan_channels:
- ircnet:perl.tw
feeds_freshports_url: http://www.freshports.org/news.php
feeds_freshports_channels:
- ircnet:bsdchat
feeds_versiontracker_url: http://www.versiontracker.com/macosx/recent.rss
feeds_versiontracker_channels:
- ircnet:osxchat

